### ISSUE TITLE
three-tracer models: inconsistent inputs.

### ISSUE THREAD

**Issue by jwschloemer** [andrewcparnell/simmr#25]
I am running a three-tracer model where each sample has values from tracers one and two, but only occasional values for tracer 3.  For example:

Sample    Tracer 1      Tracer 2    Tracer 3
1                -21              -8              NA
2                -20             -8              -2
3                -19              -8              -1

The model is based on the standard SIMMR script.  Despite inconsistent availability, the model is improved with the addition of tracer three. I gather that this is because the algorithm is run for each tracer independently, with proportions then being calculated for each tracer. I'm a bit lost in the maths on how the three tracers are then combined to provide an overall estimate of source contribution to the mixture. 

Is there a clear explanation of this process?

**Comment by andrewcparnell** [comment]
Hi jwschloemer,

The maths is exactly the same as the two isotope version. I don't know how mathematical you are, but our 2013 [Environmetrics](https://scholar.google.com/scholar?hl=en&q=Bayesian+Stable+Isotope+Mixing+models) paper shows the maths for any number of isotopes. At a very basic level with say 2 sources and 3 isotopes, it's just:

iso_1 = p_1 * s_11 + p_2 * s_21 + e
iso_2 = p_1 * s_12 + p_2 * s_22 + e
iso_3 = p_1 * s_13 + p_2 * s_23 + e

Where iso are the data isotope values, p are the dietary proportions, and s_kj is the source value for isotope j on source k. 

It's a bit more complicated than that because the above expression leads to an over-determined so you make everything stochastic and it falls out fine.

Hope that helps a bit.

Andrew
