### ISSUE TITLE
Different results with same data between old and new release

### ISSUE THREAD

**Issue by CelineLavergne** [andrewcparnell/simmr#47]
Dear developers, I really appreciate simmR and use it for my research to solve environmental problems. However, I am having some troubles lastly. I obtained very different results using simmR with similar data that I already analyzed last year or some months ago. I am wondering if the new release/update may be the reason? This is quite challenging because it may totally change the conclusion of our work. Thanks in advance, Best regards

**Comment by ChrisHarrod** [comment]
Hi Celine
I am not a part of the team, but I think you will need to provide a workable example (code, data and previous/current results) for them to see what the problem might be.
Cheers,
Chris
________________________________
From: CelineLavergne ***@***.***>
Sent: Thursday, October 26, 2023 9:45:09 AM
To: andrewcparnell/simmr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [andrewcparnell/simmr] Different results with same data between old and new release (Issue #47)


Dear developers, I really appreciate simmR and use it for my research to solve environmental problems. However, I am having some troubles lastly. I obtained very different results using simmR with similar data that I already analyzed last year or some months ago. I am wondering if the new release/update may be the reason? This is quite challenging because it may totally change the conclusion of our work. Thanks in advance, Best regards

**Comment by CelineLavergne** [comment]
Hi Chris, 
You are totally right! Thanks a lot.
I hereby add an excel file with the input and outputs of the model and the code I use. 
Maybe I did something wrong but I did not manage to figure it out, 

Thanks a lot for your help
Cheers 

[Water_Isotopes_CL.xlsx](https://github.com/andrewcparnell/simmr/files/13177919/Water_Isotopes_CL.xlsx)
[2023_SCRIPT_SIMMR_LV.txt](https://github.com/andrewcparnell/simmr/files/13177927/2023_SCRIPT_SIMMR_LV.txt)

**Comment by emmagovan** [comment]
Hi Celine, we had a small bug in a recent release that we have since fixed - have you tried rerunning this recently? If you're still having an issue let me know. Thanks!

**Comment by CelineLavergne** [comment]
Hi Emma! It seems the problem is solved. But I will let you know if something goes wrong. Thanks a lot!
